### ISSUE TITLE
Rašybos klaida mokymo medžiagoje

### ISSUE THREAD

**Issue by Aldael** [mokymai/taisymai#1]
Priede A.8 vietoj „R Markdown" yra „R Makrdown“ 
![markdown](https://user-images.githubusercontent.com/43116490/45530968-3727e780-b7f6-11e8-86bc-10371909699b.jpg)

**Comment by GegznaV** [comment]
Dėkui. Darbinėje versijoje jau pataisiau.

**Comment by GegznaV** [comment]
Jau pataisyta.

**Comment by GegznaV** [comment]
+1
