### ISSUE TITLE
Rašybos klaidos

### ISSUE THREAD

**Issue by Katazyna-Stankevic** [mokymai/taisymai#17]
1. **Glaustai aprašykite netikslumą:** rašybos klaidos
2. **Vieta** (skyriaus pavadinimas ir/arba nuoroda): skyrius "9.4 Lentelės formos keitimas", užduotis 9.14
3. **Netikslumo tekstas:** "pakementuokite"; "b8das"
4. **Siūlomo taisymo tekstas:** "pakomentuokite"; "būdas"
5. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![9 14](https://user-images.githubusercontent.com/43219517/47675270-1c50dd00-dbc2-11e8-8046-a232d7bb6974.png)

**Comment by GegznaV** [comment]
+2
