### ISSUE TITLE
Sakinio reikšmės klaida

### ISSUE THREAD

**Issue by ievajuozapaityte** [mokymai/taisymai#26]
1. **Glaustai aprašykite netikslumą:** Sakinio reikšmės klaida
2. **Vieta** (skyriaus pavadinimas ir/arba nuoroda): 6.5.1 Tidyverse sistemos funkcijos SAR duomenų formatams
3. **Netikslumo tekstas:** atskirų
4. **Siūlomo taisymo tekstas:** atskirtų
5. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![45142594_199131570980262_1289771583702827008_n](https://user-images.githubusercontent.com/43252509/47883871-6bec0e80-de37-11e8-8601-9485188e7286.png)

**Comment by GegznaV** [comment]
+1
