### ISSUE TITLE
Fakto klaida

### ISSUE THREAD

**Issue by AndriusJasinevicius** [mokymai/taisymai#29]
1. **Glaustai aprašykite netikslumą:** Graikiškos raidės pavadintos lotyniškomis
2. **Vieta** (skyriaus pavadinimas ir/arba nuoroda): https://mokymai.github.io/r-2018/r-markdown.html Lentelė 11.1
3. **Netikslumo tekstas:** "Didžiosios lotyniškos raidės"; "Mažosios lotyniškos raidės"
4. **Siūlomo taisymo tekstas:** "Didžiosios graikiškos raidės"; "Mažosios graikiškos raidės"
5. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/43240453/47900323-28b88c80-de85-11e8-86f6-f71e750185ec.png)

**Comment by GegznaV** [comment]
+1
