### ISSUE TITLE
Rašybos klaida

### ISSUE THREAD

**Issue by Aldael** [mokymai/taisymai#3]
Tekste 11.5.1 dalyje parašyta "plaukiojantį" vietoj "plaukiojantį".
Taip pat "Paramertas".

![klaida](https://user-images.githubusercontent.com/43116490/47550322-9570db80-d907-11e8-9952-b1a49e22262c.png)

**Comment by GegznaV** [comment]
Ačiū.

**Comment by GegznaV** [comment]
+1
