### ISSUE TITLE
Rašybos klaida 

### ISSUE THREAD

**Issue by iurbon** [mokymai/taisymai#41]
1. **Glaustai aprašykite netikslumą:** rašybos klaida
2. **Vieta** (skyriaus pavadinimas ir/arba nuoroda): 11.6.2 Markdown lentelių pavyzdžiai
3. **Netikslumo tekstas:** "lentelės tirėtų būti"
4. **Siūlomo taisymo tekstas:** turėtų
5. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![klaida1](https://user-images.githubusercontent.com/43253802/48157393-25cff880-e2d8-11e8-8acf-f33782381bd5.png)

**Comment by GegznaV** [comment]
Tas pats kaip #38
