### ISSUE TITLE
Rašybos klaida

### ISSUE THREAD

**Issue by AndriusJasinevicius** [mokymai/taisymai#43]
1. **Glaustai aprašykite netikslumą:** Vietoj "other" parašyta "ohter"
2. **Vieta** (skyriaus pavadinimas ir/arba nuoroda): https://mokymai.github.io/r-2018/duomenu-parengimas.html
3. **Netikslumo tekstas:** ## $ race <chr> "black", "ohter", "white", "white", "white", "ohter", "wh...
4. **Siūlomo taisymo tekstas:** ## $ race <chr> "black", "other", "white", "white", "white", "other", "wh...
5. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/43240453/48161607-a9431700-e2e3-11e8-8d38-351050c8460f.png)

**Comment by GegznaV** [comment]
Tas pats kaip #40
