### ISSUE TITLE
Trūksta tarpų tarp žodžių

### ISSUE THREAD

**Issue by GabijaSakalyte** [mokymai/taisymai#44]
Temos pavadinime rašykite netikslumo esmę, kuri kitiems skaitytojams padėtų bent iš dalies identifikuoti netikslumą neatsidarius temos, pvz., *Klaida žodyje "kopppiuteris"* ar *Praleistas žodis "tačiau"*.

1. **Glaustai aprašykite netikslumą:** Reikėtų tarpelių tarp žodžių
2. **Vieta:** 5.4 Kodo rašymo stilius
3. **Netikslumo tekstas:** betjosdarokodąlabiausuprantamą irdarbassutokiukodumažiauvargina.
4. **Siūlomo taisymo tekstas:** bet jos daro kodą labiau suprantamą ir darbas su tokiu kodu mažiau vargina.
5. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="660" alt="klaidos" src="https://user-images.githubusercontent.com/43230446/48222315-f9ca7b00-e39c-11e8-8c2f-928f2d13e37e.PNG">

**Comment by GegznaV** [comment]
Šioje vietoje tokia ir buvo mintis.
