### ISSUE TITLE
Netinkamas šaltinių citavimo stilius

### ISSUE THREAD

**Issue by RPrakapaite** [mokymai/taisymai#63]
1. **Glaustai aprašykite netikslumą:** Vartojamas neįprastas, netinkamas šaltinių citavimo stilius, išskiriant tikslų leidinio puslapį vienu skliausteliu. Taip pat, "and" neturėtų būti vartojamas cituojant tekstą, kuris yra lietuviškas. Praktikoje įprasta atskirti autorių, leidimo metus bei tikslią cituojamą vietą kableliais. 
2. **Vieta** (skyriaus pavadinimas ir/arba nuoroda): 13.2.1.;
3. **Netikslumo tekstas:** (Čekanavičius and Murauskas 2008) p.33); (Venclovienė 2010) p. 175).
4. **Siūlomo taisymo tekstas:** citavimą rašyti vienuose skliausteliuose: (Čekanavičius ir Murauskas, 2008, p.33) http://www.xn--altiniai-4wb.info/files/kalba/KL00/Lietuvi%C5%B3_kalbos_%C5%BEinynas._Skyryba.KL0001.pdf

![image](https://user-images.githubusercontent.com/45017439/49704721-3220db80-fc1f-11e8-8e80-dc8456ae0b58.png)

**Comment by RPrakapaite** [comment]
To pačio pobūdžio siūlymas tinkamai cituoti lietuvių autorių šaltinius - "and" neturėtų būti vartojamas cituojant tekstą, kuris yra lietuviškas. 
Vieta: C R sesijos informacija.
Netikslumo tekstas: Čekanavičius, Vydas, **and** Gediminas Murauskas.
Taisymas: Čekanavičius, Vydas, ir Gediminas Murauskas.

![image](https://user-images.githubusercontent.com/45017439/49705088-2c79c480-fc24-11e8-9ac8-7468c81df64b.png)

**Comment by GegznaV** [comment]
Dėkui. Deja tai žinoma dabar naudojamo citavimų variklio problema.

**Comment by GegznaV** [comment]
Dalį pataisiau.
